SELECT CHILD.ITEM_ID, CHILD.ITEM_NAME, CHILD.RARITY
FROM ITEM_TREE IT
JOIN ITEM_INFO PARENT ON IT.PARENT_ITEM_ID = PARENT.ITEM_ID
JOIN ITEM_INFO CHILD ON IT.ITEM_ID = CHILD.ITEM_ID
WHERE PARENT.RARITY = 'RARE'
ORDER BY CHILD.ITEM_ID DESC