SELECT COUNT(F.FISH_TYPE) AS 'FISH_COUNT', FN.FISH_NAME AS 'FISH_NAME'
FROM FISH_NAME_INFO FN
    JOIN FISH_INFO F
    ON FN.FISH_TYPE = F.FISH_TYPE
GROUP BY FN.FISH_TYPE, FN.FISH_NAME
ORDER BY COUNT(F.FISH_TYPE) DESC