# SELECT SUM(HG.SCORE) AS 'SCORE', 
#         HE.EMP_NO, 
#         HE.EMP_NAME,
#         HE.POSITION,
#         HE.EMAIL
# FROM HR_EMPLOYEES HE
# JOIN HR_GRADE HG
#     ON HE.EMP_NO = HG.EMP_NO
# GROUP BY HE.EMP_NO
# HAVING SCORE = (
#     SELECT MAX(TOTAL)
#     FROM (
#         SELECT SUM(SCORE) AS 'TOTAL'
#         FROM HR_GRADE
#         GROUP BY EMP_NO
#     ) T
# )

WITH SCORE_SUM AS (
    SELECT EMP_NO, SUM(SCORE) AS TOTAL_SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT SS.TOTAL_SCORE AS 'SCORE', 
        HE.EMP_NO, 
        HE.EMP_NAME,
        HE.POSITION,
        HE.EMAIL
FROM SCORE_SUM SS
JOIN HR_EMPLOYEES HE
    ON SS.EMP_NO = HE.EMP_NO
WHERE SS.TOTAL_SCORE = (SELECT MAX(TOTAL_SCORE) FROM SCORE_SUM)